version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    ports:
      - 80:80
    volumes:
      - ./api:/var/www/html/api
    depends_on:
      - mysql
      - php

  mysql:
    image: mariadb:10.5
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./mysql:/var/lib/mysql

  php:
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ./api:/var/www/html/api

  composer:
    build:
      context: .
      dockerfile: composer.dockerfile
    volumes:
      - ./api:/var/www/html/api
    working_dir: /var/www/html/api
    entrypoint: ["composer"]

  artisan:
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ./api:/var/www/html/api
    working_dir: /var/www/html/api
    depends_on:
      - mysql
    entrypoint: ["php", "/var/www/html/api/artisan"]